Updates and reorganizing

diff --git a/docker/Dockerfile.base b/docker/Dockerfile.base
--- a/docker/Dockerfile.base
+++ b/docker/Dockerfile.base
@@ -5,28 +5,55 @@
 ## ARGS are env vars that are *only available* during the Docker build.
 ## They can be modified at Docker build time via '--build-arg VAR="something"'.
 ARG REGISTRY=docker.io/library
-ARG BASE_IMAGE=ubuntu:22.04
+ARG IMAGE_BASE=ubuntu:22.04
 
-FROM ${REGISTRY}/${BASE_IMAGE} AS base
+FROM ${REGISTRY}/${IMAGE_BASE} AS base
 
+## Set Bash as the default shell.
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+
+## Step 1.
+## Configure APT for running in Docker.
+##
+## 1) By default, APT tries to use IPv6 also which usually
+##    causes issues in Docker, so force APT to always use IPv4.
+## 2) Don't install recommended/suggested packages.
+RUN <<EOF cat > /etc/apt/apt.conf.d/99force-ipv4
+Acquire::ForceIPv4 "true";
+EOF
+RUN <<EOF cat > /etc/apt/apt.conf.d/99no-recommends
+APT::Install-Recommends "0";
+APT::Install-Suggests "0";
+EOF
+
+## APT is running in a script/noninteractive environment.
+## We want this to be set only during build, not in the
+## shell environment of the final image, hence we set it
+## using ARG which does not persist after build.
+ARG DEBIAN_FRONTEND=noninteractive
+
+
+## Step 2.
+## Install HTTPS support for APT and other needed packages,
+## then upgrade all installed packages.
+RUN <<EOF
+    set -ex
+    apt-get update -y
+    apt-get install -y \
+      apt-transport-https ca-certificates \
+      software-properties-common debconf-utils
+    apt-get upgrade -y
+EOF
+
+## Step 3.
+## Install and configure locale, keyboard layout and other related packages.
 ENV TZ='Europe/Helsinki' \
     LC_ALL='C.UTF-8' \
     LANG='en_US.UTF-8' \
     LANGUAGE='en_US:en:C'
 
-## Step 1. Prepare base image.
-ARG DEBIAN_FRONTEND=noninteractive
-
-## Install basic APT stuff and upgrade
-RUN apt-get -y update && \
-    apt-get -y upgrade && \
-    apt-get install -y --no-install-recommends \
-      apt-transport-https \
-      ca-certificates \
-      software-properties-common \
-      debconf-utils
-
-## Autoconfigure packages during install with 'debconf-set-selections'
+## Autoconfigure locale, keyboard layout etc config during package 
+## install using 'debconf-set-selections'.
 RUN debconf-set-selections <<EOF
 keyboard-configuration	keyboard-configuration/layout	select	Finnish
 keyboard-configuration	keyboard-configuration/variant	select	Finnish
@@ -43,85 +70,85 @@ tzdata	tzdata/Zones/Etc	select	UTC
 tzdata	tzdata/Zones/Europe	select	Helsinki
 EOF
 
-## Install locale stuff
-RUN apt-get install -y --no-install-recommends \
-      locales \
-      language-pack-en \
-      keyboard-configuration \
-      console-setup \
+RUN <<EOF
+    set -ex
+    apt-get install -y \
+      locales language-pack-en \
+      keyboard-configuration console-setup \
       tzdata
-RUN localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
+    localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
+EOF
 
-## Install basic packages and cleanup
-RUN apt-get install -y --no-install-recommends \
-      curl \
-      file \
-      git \
-      git-lfs \
-      gnupg2 \
-      jq \
-      nano \
-      rsync \
-      wget \
-    && apt-get clean autoclean -y \
-    && apt-get autoremove -y \
-    && rm -rf /var/lib/apt/lists/*
+## Step 4.
+## Install basic packages and tools, and do cleanup.
+RUN <<EOF
+    set -ex
+    apt-get install -y \
+      bash curl file \
+      git git-lfs gnupg2 \
+      jq nano rsync \
+      wget tar zstd bzip2
+    apt-get clean autoclean -y
+    apt-get autoremove -y
+    rm -rf /var/lib/apt/lists/*
+EOF
 
-FROM base as builder_base
 
-## Step 2. Prepare builder image.
-ARG DEBIAN_FRONTEND=noninteractive
-
-RUN apt-get update -y && \
-    apt-get install -y --no-install-recommends \
-      asciidoc \
-      bash \
-      binutils \
-      bison \
-      build-essential \
-      bzip2 \
-      ccache \
-      flex \
-      g++ \
-      g++-multilib \
-      gawk \
-      gcc \
-      gcc-multilib \
-      genisoimage \
-      gettext \
-      gzip \
-      help2man \ 
-      intltool \
-      libdw-dev \
-      libelf-dev \
-      libncurses5-dev \
-      libncursesw5-dev \
-      libssl-dev \
-      patch \
-      perl-modules \ 
-      pv \
-      pwgen \
-      python-is-python3 \
-      python3 \
-      python3-cryptography \
-      python3-dev \
-      python3-pip \
-      python3-pyelftools \
-      python3-setuptools \
-      python3-venv \
-      qemu-utils \
-      signify-openbsd \
-      subversion \
-      swig \
-      tar \
-      unzip \
-      xsltproc \
-      xxd \
-      zlib1g-dev \
-      zstd \
-    && apt-get clean autoclean -y \
-    && apt-get autoremove -y \
-    && rm -rf /var/lib/apt/lists/*
-
-ENV GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
+#FROM base as builder_base
+#
+### Step 2. Prepare builder image.
+#ARG DEBIAN_FRONTEND=noninteractive
+#
+#RUN apt-get update -y && \
+#    apt-get install -y --no-install-recommends \
+#      asciidoc \
+#      bash \
+#      binutils \
+#      bison \
+#      build-essential \
+#      bzip2 \
+#      ccache \
+#      flex \
+#      g++ \
+#      g++-multilib \
+#      gawk \
+#      gcc \
+#      gcc-multilib \
+#      genisoimage \
+#      gettext \
+#      gzip \
+#      help2man \ 
+#      intltool \
+#      libdw-dev \
+#      libelf-dev \
+#      libncurses5-dev \
+#      libncursesw5-dev \
+#      libssl-dev \
+#      patch \
+#      perl-modules \ 
+#      pv \
+#      pwgen \
+#      python-is-python3 \
+#      python3 \
+#      python3-cryptography \
+#      python3-dev \
+#      python3-pip \
+#      python3-pyelftools \
+#      python3-setuptools \
+#      python3-venv \
+#      qemu-utils \
+#      signify-openbsd \
+#      subversion \
+#      swig \
+#      tar \
+#      unzip \
+#      xsltproc \
+#      xxd \
+#      zlib1g-dev \
+#      zstd \
+#    && apt-get clean autoclean -y \
+#    && apt-get autoremove -y \
+#    && rm -rf /var/lib/apt/lists/*
+#
+#ENV GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
 
